### ISSUE TITLE
Serial to radio.

### ISSUE THREAD

**Issue by runahue** [4Z1KD/HamSwitch#1]
Tnx for your project.
I will try on next days.

Do you connect directly Kenwood RS-232 to Arduino?
Arduino uses 5v and standard serial port (i think) is 12v.
Do you use a max232?

Thank's a lot.

73 de EA5BZ

**Comment by 4Z1KD** [comment]
Hi Ruben,
I use MAX232 for the interface (Not shown in the diagram)

let me know if you use HamSwitch and send some photos :)
73, Gil 4Z1KD

**Comment by runahue** [comment]
Hello Gil.

Yes… i am using it ¡!
I made some modifications.
Now i can use it auto or manual.

Attached some photos.

Thank’s for your work ¡

😊

----------
Ruben Navarro Huedo - EA5BZ
runahue@gmail.com

De: Gil (4Z1KD)
Enviado: lunes, 17 de septiembre de 2018 14:03
Para: 4Z1KD/HamSwitch
CC: runahue; Author
Asunto: Re: [4Z1KD/HamSwitch] Serial to radio. (#1)

Hi Ruben,
I use MAX232 for the interface (Not shown in the diagram)
let me know if you use HamSwitch and send some photos :)
73, Gil 4Z1KD

**Comment by lu6etb** [comment]
Hi Gil,

Thanks for this project.

Could you please give me more details about how to connect to the radio?
Do you have a diagram?

Thanks
73 de Arturo, LU6ETB

**Comment by 4Z1KD** [comment]
Hi Arturo,
I am sorry for the late response.
The way to connect HamSwitch to your radio is either directly using the TTL
pins to the radio's CAT input socket or via TTL to RS232 converter.

Which radio do you use?
For instance, I use this method to connect to my FT857D:
[image: image.png]

And my friend uses the other method for his FT991:
[image: image.png]

Let me know if you have any other questions.
73,
Gil 4Z1KD
